### ISSUE TITLE
After deleting a project, you can not create an item with the same name as the deleted one

### ISSUE THREAD

**Issue by inspuradmin** [inspursoft/board#200]
In GitLab by @guyingyan on Nov 7, 2017, 10:13

error info as below:
1. ./dashboard_test.go:4: imported and not used: "git/inspursoft/board/src/apiserver/controller"
./dashboard_test.go:5: imported and not used: "testing"

2. git/inspursoft/board/src/collector/cmd/app/appflag_test.go
info:
2017/11/07 09:37:14 DbPort non
2017/11/07 09:37:14 KubeIp non
2017/11/07 09:37:14 KubePort non
2017/11/07 09:37:14 DbPass non
2017/11/07 09:37:14 DbType non
2017/11/07 09:37:14 DbIp non
url is  http://:/version
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xf1020a]

goroutine 1 [running]:
git/inspursoft/board/src/collector/service/collect.pingK8sApiLink()
	/home/boardTest/wangkun_lc/src/git/inspursoft/board/src/collector/service/collect/TableMain.go:44 +0x2aa
git/inspursoft/board/src/collector/service/collect.SetInitVar(0x0, 0x0, 0x0, 0x0)
	/home/boardTest/wangkun_lc/src/git/inspursoft/board/src/collector/service/collect/TableMain.go:33 +0x19a
git/inspursoft/board/src/collector/cmd/app.init.1()
	/home/boardTest/wangkun_lc/src/git/inspursoft/board/src/collector/cmd/app/appflag.go:100 +0x56
git/inspursoft/board/src/collector/cmd/app.init()
	/home/boardTest/wangkun_lc/src/git/inspursoft/board/src/collector/cmd/app/appflag_test.go:16 +0x6c
main.init()
	git/inspursoft/board/src/collector/cmd/app/_test/_testmain.go:46 +0x53

**Comment by inspuradmin** [comment]
In GitLab by @yhua123 on Nov 8, 2019, 07:40

by design now, will use project_id as key value in the future

**Comment by inspuradmin** [comment]
In GitLab by @sokril on Nov 8, 2019, 08:13

closed

**Comment by inspuradmin** [comment]
In GitLab by @sokril on Nov 8, 2019, 08:13

assigned to @luotian-github
