### ISSUE TITLE
board always show old dockerfile info when building the image

### ISSUE THREAD

**Issue by inspuradmin** [inspursoft/board#452]
In GitLab by @luotian-github on Jun 4, 2018, 16:12

Generic Cause
Building remotely on slave in workspace /data/jenkins_node/workspace/demo
ERROR: java.nio.file.NoSuchFileException: /data/jenkins_node/workspace/demo/.travis.yml (IOError)
org/jruby/RubyIO.java:2902:in `read'
/var/jenkins_home/plugins/travis-yml/WEB-INF/classes/vendor/gems/bundler/../gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/filepath.rb:27:in `read'
/var/jenkins_home/plugins/travis-yml/WEB-INF/classes/models/travis_yml_script.rb:14:in `build'
/var/jenkins_home/plugins/travis-yml/WEB-INF/classes/models/travis_yml_builder.rb:27:in `perform'
/var/jenkins_home/plugins/travis-yml/WEB-INF/classes/vendor/gems/bundler/../gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:14:in `perform'
/var/jenkins_home/plugins/travis-yml/WEB-INF/classes/vendor/gems/bundler/../gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:22:in `boolean_result'
/var/jenkins_home/plugins/travis-yml/WEB-INF/classes/vendor/gems/bundler/../gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:13:in `perform'

Build step 'Build using .travis.yml' marked build as failure
Finished: FAILURE

**Comment by inspuradmin** [comment]
In GitLab by @sokril on Nov 8, 2019, 08:22

closed

**Comment by inspuradmin** [comment]
In GitLab by @sokril on Nov 8, 2019, 08:22

assigned to @wknet123
